### ISSUE TITLE
Set up documentation

### ISSUE THREAD

**Issue by ilancoulon** [corail-research/SeaPearl.jl#102]
Before/while becoming public, we should set up a nice documentation using Documenter.jl.
There are already a lot of comments in the code that should allow the documentation to be quite full very quickly.
We just need to write a few pages to explain the overall project (of course using some parts of the paper would be a good idea imo).

**Comment by 3rdCore** [comment]
Some important documentation is still missing in some parts of the code. This will be treated in the following weeks.
