### ISSUE TITLE
Bug in the TSPTW test

### ISSUE THREAD

**Issue by PierreTsr** [corail-research/SeaPearl.jl#122]
An inconsistant behavior has been spotted on the test `Search known instance` line 166 in `test/datagen/tsptw.jl`.

The test aims at checking the correct generation of tsptw instances, by solving already resolved problems and controling the existence of a solution. However, this test randomly fails despite the specification of a seed, which make the construction of the instance deterministic.

It appears that the issue doesn't come from the problem generation, but from the CP solver itself. After a quick investigation, I managed to find the point where the bug occurs in the search tree. Indeed, as both heuristics are deterministic in this test, the solver always explores the same path in the search tree. But at some point, a variable assignment triggers a random behavior in `fixpoint!` resulting in a valid or invalid assignment without any obvious explanation.

I tweaked the original test a little bit to reproduce the bug:
``` julia
using SeaPearl

trailer = SeaPearl.Trailer()
model = SeaPearl.CPModel(trailer)

n_city = 21
grid_size = 150
max_tw_gap = 3
max_tw = 8

generator = SeaPearl.TsptwGenerator(n_city, grid_size, max_tw_gap, max_tw)

SeaPearl.fill_with_generator!(model, generator; seed=42)

SeaPearl.assign!(model.variables["a_1"], 19)
SeaPearl.assign!(model.variables["a_2"], 20)
SeaPearl.assign!(model.variables["a_3"], 16)
SeaPearl.assign!(model.variables["a_4"], 11)
SeaPearl.assign!(model.variables["a_5"], 14)
SeaPearl.assign!(model.variables["a_6"], 8)
SeaPearl.assign!(model.variables["a_7"], 17)

SeaPearl.fixPoint!(model)

SeaPearl.assign!(model.variables["a_8"], 5)

status, prunedDomains = SeaPearl.fixPoint!(model, SeaPearl.getOnDomainChange(model.variables["a_8"]))
```
On my system on successive runs, `fixPoint!` returns `false` a third of the time.
On every failed run I've had in the original test, this last assignment always was the one triggering the failure.

I double-checked that the distance matrix and time_windows generation was consistant (supposedly the only variables randomly generated in `TsptwGenerator`). I haven't been able to check that the initialization of every variable/constraint is the same at each run, but they aren't suppose to be random. I haven't been able to check yet which constraint/part of `fixPoint!` is responsible for this behavior.

However, this part becomes tricky because there are 1500+ constraints in the model and `fixPoint!` doesn't seem to call them all in the same order. I'll keep digging and will post any new lead.

My current leads are:

- a failing constraint pruning to much values
- a mishandling of a variable in `fixPoint!`

**Comment by PierreTsr** [comment]
@qcappart it doesn't seem to come from the seed as you first supposed, and it is probably deeper than we originately thought.

**Comment by PierreTsr** [comment]
I've spend a lot of efforts trying to reduce the field of possible errors. I've came out with this relatively short sequence of constraint propagations, which when applied after the assignment of `a_8` to `5` triggers an impossible state.

``` julia
SeaPearl.SetDiffSingleton: m_9 == m_8 \ {a_8}
SeaPearl.SetDiffSingleton: m_10 == m_9 \ {a_9}
SeaPearl.SetDiffSingleton: m_11 == m_10 \ {a_10}
SeaPearl.InSet: a_10 in m_10
SeaPearl.Element2D: maxtrix[a_10, SEAPEARL_one] == lower_ai_10
SeaPearl.BinaryMaximumBC: t_11 == max(td_10lower_ai_10)
SeaPearl.isLessOrEqual: s_t_11_18 <=> t_11 <= upper_tw_18
SeaPearl.BinaryOr: s_t_11_18 || ¬18_in_m_11
SeaPearl.ReifiedInSet: 18_in_m_11 <=> index_18 in m_11
SeaPearl.SetDiffSingleton: m_11 == m_10 \ {a_10}
SeaPearl.InSet: a_10 in m_10
SeaPearl.Element2D: maxtrix[a_10, SEAPEARL_one] == lower_ai_10
SeaPearl.BinaryMaximumBC: t_11 == max(td_10lower_ai_10)
SeaPearl.ReifiedInSet: 9_in_m_11 <=> index_9 in m_11
SeaPearl.isLessOrEqual: s_t_11_9 <=> t_11 <= upper_tw_9
SeaPearl.BinaryOr: s_t_11_9 || ¬9_in_m_11
SeaPearl.isLessOrEqual: s_t_11_9 <=> t_11 <= upper_tw_9
SeaPearl.ReifiedInSet: 9_in_m_11 <=> index_9 in m_11
SeaPearl.SetDiffSingleton: m_11 == m_10 \ {a_10}
SeaPearl.InSet: a_10 in m_10
SeaPearl.Element2D: maxtrix[a_10, SEAPEARL_one] == lower_ai_10
SeaPearl.BinaryMaximumBC: t_11 == max(td_10lower_ai_10)
SeaPearl.Element2D: maxtrix[a_10, SEAPEARL_one] == lower_ai_10
SeaPearl.SetDiffSingleton: m_11 == m_10 \ {a_10}
SeaPearl.ReifiedInSet: 9_in_m_11 <=> index_9 in m_11
SeaPearl.SetDiffSingleton: m_10 == m_9 \ {a_9}
```
(with enhanced display of constraints, on branch `feature/constraint_readability`)

However, I haven't been able yet to understand what is going wrong here. Under the normal behavior, we should have `a_9 = 18` and `a_10 = 18` at the end of the fixpoint. But that's not where these constraints lead.

**Comment by PierreTsr** [comment]
I finally found out what was going on!
In the propagation of the constraint `SetDiffSingleton` (as supposed by @ilancoulon ), the solver doesn't have the correct behavior in a particular case:
``` julia
julia> r[19]
SeaPearl.SetDiffSingleton: m_11 == m_10 \ {a_10}, active = StateObject{Bool}: true
   m_11=req=Set{Int64}(); poss=Set([4, 13, 21, 2, 6, 7, 15, 12, 10, 3])
   m_10=req=Set{Int64}(); poss=Set([7, 12, 4, 13, 6, 2, 21, 10, 9, 15, 3])
   a_10=[21 2 3 4 13 6 7 15 9 10 12 ]


julia> SeaPearl.propagate!(r[19], toPropagate, p)
true

julia> r[19]
SeaPearl.SetDiffSingleton: m_11 == m_10 \ {a_10}, active = StateObject{Bool}: true
   m_11=req=Set{Int64}(); poss=Set([4, 13, 21, 2, 6, 7, 15, 12, 10, 3])
   m_10=req=Set{Int64}(); poss=Set([4, 13, 6, 2, 7, 21, 15, 12, 10, 3])
   a_10=[21 2 3 4 13 6 7 15 9 10 12 ]
```
There, rather than pruning the value `9` from `m_10`, the solver shouldn't do anything imo, as neither of the set are fixed. I'm not entirely sure if we should assign `9` to `a_10`, because there are some cases where it could lead to wrong behavior if both sets are pruned later. What do you think?

**Comment by qcappart** [comment]
Good catch ! Yes you're right: `9` should not be pruned from `m_10` domain. Maybe I misinterpret the print, but it seems that the both sets are fixed (i.e., it is an non-empty set with fixed values) ? But even in in this case the value should not be pruned.

If both sets are fixed (but I am not sure it is the case), I think `a_10=9` is the only option. Otherwise, you are right we cannot do the assignation.

**Comment by PierreTsr** [comment]
Actually the print is misleading (working on it) and neither of the sets are fixed, so nothing could be inferred for `a_10`.

I've got a fix ready for `SetDiffSingleton` but maybe we should work on a more generic constraint `SetDiff`, as Ilan suggested?

**Comment by qcappart** [comment]
Great ! I'll take a look at the PR. But definitively, a more generic `SetDiff` that can compute the difference of two arbitrary sets will be a nice addition.
