### ISSUE TITLE
metricsFun can not handle more than 1 classic heuristic

### ISSUE THREAD

**Issue by 3rdCore** [corail-research/SeaPearl.jl#134]
*BUG* While running experiences, the metricsFun doesn't make any difference between all possible classic heuristic while filling MetricsArray, making the results not relevant for analysis. 

SeaPearl should maybe provide some classic Metrics Functions to help the user analyze the performance of his model. -

**Comment by qcappart** [comment]
This one has been resolved with your previous merged PR, right ?

**Comment by 3rdCore** [comment]
Indeed, it has been fixed since PR#143.
