### ISSUE TITLE
Possible TableCT optimisation

### ISSUE THREAD

**Issue by PierreTsr** [corail-research/SeaPearl.jl#137]
After discussing the problem _Eternity 2_ with @tomsander1998 we figured out a potential optimisation of the table constraint.

Indeed, in _Eternity 2_, each piece is represented by a tuple of 5 variables which must obey a table constraint. However, each table constraint has the same table and thus the same supports.

With the current implementation, the table is copied each time, and the support is rebuilt each time which `#pieces` times more memory than if we had a single table/support dictionnary.

What should be done is defining a new constructor for `TableConstraint` that take a table & support dictionnary as input and set the corresponding attributes as references to these.

**Comment by qcappart** [comment]
Is it related to what is proposed in this paper: https://link.springer.com/chapter/10.1007/978-3-319-98334-9_14 ?

**Comment by PierreTsr** [comment]
> 
> 
> Is it related to what is proposed in this paper: https://link.springer.com/chapter/10.1007/978-3-319-98334-9_14 ?

I don't think it is. This issue is purely related to our implementation and to the management of the attributes of the `TableConstraint`. What I propose is to share an array and a dictionnary between many constraints rather than copying them each time.
