### ISSUE TITLE
Current base NN dense layer doesn't use any activation functions....

### ISSUE THREAD

**Issue by 3rdCore** [corail-research/SeaPearl.jl#155]
The basic agent declaration uses GNN and Dense Neural Network for Q approximation. We discover that the dense layer doesn't include activation functions : The dense NN only performs a linear regression on our data...

**Comment by qcappart** [comment]
To which declaration are you referring to ? You're right, non-linear activation should be added between layers (add ReLU), but I guess it has to be done when defining the specific agent network (i.e., in SeaPearlZoo examples)

**Comment by 3rdCore** [comment]
We figured out it was not natively implement during the agent declaration. 
The agent approximator declaration : 
![image](https://user-images.githubusercontent.com/59280588/121215605-2a713a80-c84e-11eb-917e-79264730994e.png)
The `Flux.Dense` base constructor : 
![image](https://user-images.githubusercontent.com/59280588/121215587-25ac8680-c84e-11eb-925e-35287ee6834b.png)

**Comment by tomsander1998** [comment]
yes ! it has been changed for some of the examples and I can add activation functions for the other ones. This is more of an issue for SeaPearlZoo not SeaPearl right?

**Comment by 3rdCore** [comment]
Indeed, my bad, it should have been on SeaPearlZoo github.
