### ISSUE TITLE
[CP][Boolean Operator] Implement truth-functional operator of logical conjunction : ∧

### ISSUE THREAD

**Issue by 3rdCore** [corail-research/SeaPearl.jl#200]
In order to be able to model more complex CP problems, it would be great, given two `AbstractBoolVar x` and `y` to be able to automatically generate a `BoolVarView z` such that : `z = x ∧ y` 

This would be a good feature to facilitate future CP problem implementation and can be a nice good first issue for a newcomer.

**Comment by 3rdCore** [comment]
It seems that the overall logic of SeaPearl regarding boolean variables is not _formula_-oriented but constraint-oriented. 

For example, the actual version of SeaPearl doesn't support the boolean constrain of the form : `x ⟹ ¬( y ∧ z )` or any kind of more complex formula that contains for than two Boolean variables. This is due to the fact that any logical connective (that is already been implemented) between 2 logical formulas is considered as a `SeaPearl.Constraint` rather than considering the newly created complex formula as a new `SeaPearl.BoolVar` that needs to remain _True_ during the solving. By doing so, we could possibly create a very complex boolean formula out of many Atomic boolean variables.

In order to redefine the way SeaPearl handles Boolean variables, one needs to : 
-remove constraints that models one of the five logical connectives: `¬, ∧ , ∨ , ⟹ , ⟺`
- implement a sort of `BoolVarView ` for each of the five logical connectives: `¬, ∧ , ∨ , ⟹ , ⟺` and overwrite (if possible) the associated 5 operators.
- implement only one (or two for a more User-friendly interface) constraint of the form `SeaPearl.IsTrue(C::AbstractBoolVar)` ( and `SeaPearl.IsFalse(C::AbstractBoolVar)`)

This required a bit of refacto and maybe the implementation of 2 new struct `SeaPearl.AtomicVar` and `SeaPearl.ComplexVarView` but could open some pretty interesting fields in terms of problem modeling. 

What do you thing of these modifications @qcappart ?  Let me know if you think that my intuition is correct. In that case, I could open many little issues regarding this milestone.

**Comment by qcappart** [comment]
Looking at the documentation of Gecode (https://www.gecode.org/doc-latest/reference/group__TaskModelIntRelBool.html), it seems that they are also restricted to constraints with 2 BoolVar. I guess that the purpose is to have propagators easier to implement (and not a single propagator working for any kind of boolean formula). My suggestion is to stick with this solution on the propagation side. 

What we can do is to add a kind of modelling layer that will do the splitting for us and will be hidden for the user (in a similar fashion as what minizinc is doing during the flatzinc transformation).

**Comment by louis-gautier** [comment]
SeaPearl has currently only 2 constraints working with boolean variables:

**Comment by louis-gautier** [comment]
SeaPearl seems to currently have only 2 implemented constraints working with Boolean variables: 
- `binaryor(x,y)` which ensures that `x ∨ y = 1`
- `isbinaryor(x,y,b)` which ensures that `x ∨ y = b`

Should we implement new constraints associated to the `¬, ∧ , ⟹ and ⟺` operators?
(Then when this is done we could potentially add a modeling layer to transform complex expressions to constraints usin these operators.)

**Comment by qcappart** [comment]
Indeed, it would be great to have support for the other boolean operators. Looking at the documentation of [Gecode](https://www.gecode.org/doc-latest/reference/group__TaskModelInt.html#ga90da089a2d573ef55f5f8ee3a8bd0c67), we can have:

_BOT_AND | Conjunction.
BOT_OR | Disjunction.
BOT_IMP | Implication.
BOT_EQV | Equivalence.
BOT_XOR | Exclusive or._
