### ISSUE TITLE
Generic reward encouraging smart exploration of the tree.

### ISSUE THREAD

**Issue by louis-gautier** [corail-research/SeaPearl.jl#216]
Test it and make it work on:
- [x] nqueens
- [x] graphcoloring
- [x] TSPTW

**Comment by louis-gautier** [comment]
Associated PR is #226

**Comment by 3rdCore** [comment]
I'm wondering if we should wait for the issue #227 to be solved before trying to **evaluate** the improvement of that new reward or even discuss the value of the different importance weights used in the reward. 

What do you think of this?

**Comment by louis-gautier** [comment]
I don't think so because it is really hard to make the agent learn in problems with objective functions with `CPReward`. We can stick with `CPReward` with problems like nqueens for example, but I think we will need this reward to evaluate the improvement of learning with the new heterogeneous pipeline.
