### ISSUE TITLE
Implementation of the heterogeneous graph

### ISSUE THREAD

**Issue by gostreap** [corail-research/SeaPearl.jl#227]
Practical follow-up to issue #225. 

*The objective is to list what needs to be done to obtain a representation of the problem in the form of a tripartite heterogeneous graph, from the files created to the functions to be implemented.*

It seems to me that four new classes should absolutely be created.
- `HeterogeneousStateRepresentation`, the heterogeneous version of `DefaultStateRepresentation`.
- `HeterogeneousTrajectoryState`, the heterogeneous version of `DefaultTrajectoryState`.
- `HeterogeneousFeaturedGraph`, the heterogeneous version of `FeaturedGraph`.
- `HeterogeneousBatchedFeaturedGraph`, the heterogeneous version of `BatchedFeaturedGraph`.

For the `HeterogeneousStateRepresentation`, 4 major functions must be rewritten:
- [x] the constructor
- [x] `initChosenFeatures!`
- [x] `featurize!`
- [x] `update_features!`

For the `HeterogeneousTrajectoryState`, we must work on:
- [x] the constructor taking as argument an instance of `HeterogeneousStateRepresentation`.
- [x] the batched version of the `HeterogeneousTrajectoryState`.
- [x] the two functors taking either an instance or an instance vector of `HeterogeneousStateRepresentation`.

For the `HeterogeneousFeaturedGraph`, it will be necessary to:
- [x] write a constructor allowing to build an instance from a `HeterogeneousStateRepresentation`.
  - [x]  build the adjacency matrices from the `CPLayerGraph`
- [x] write `check_dimensions`, to check that the dimensions of the different matrices are homogeneous.
- [x] write compatibility functions with `LightGraphs`.

For the `HeterogeneousBatchedFeaturedGraph`, it will be necessary to:
- [x] write a constructor allowing to build an instance from a `HeterogeneousTrajectoryState`.
- [x] write `check_dimensions`, to check that the dimensions of the different matrices are homogeneous.
- [x] write compatibility functions with `LightGraphs`.

*See the [heterogeneous branch](https://github.com/corail-research/SeaPearl.jl/tree/heterogeneous).*

**Comment by 3rdCore** [comment]
Nice tracking of the development !

**Comment by louis-gautier** [comment]
What remains to be done:

- [ ] Define a new CPNN for the heterogeneous pipeline: `HeterogeneousCPNN`
- [ ] Define new agents
