### ISSUE TITLE
Try to give some metrics as input of the RL agent

### ISSUE THREAD

**Issue by felixchalumeau** [corail-research/SeaPearl.jl#34]
It could be interesting to try to add some metrics to the input of the RL agent, basically concatenating metrics to an existing state vector. 

It's far from being a priority but I'll put it here as it could be interesting to try one day or another.

**Comment by PierreTsr** [comment]
I think this feature has been taken care of by the addition of the `globalFeatures` in #158. @3rdCore @tomsander1998 do you agree ?

**Comment by 3rdCore** [comment]
Yes. Indeed, several examples using `globalFeatures ` have been implemented in [SeaPearlZoo](https://github.com/corail-research/SeaPearlZoo) : [features.jl](https://github.com/corail-research/SeaPearlZoo/blob/master/learning_cp/eternity2/features.jl) of the Eternity II example.

but are we sure that global features are updated as the research progresses ? I'm not sure how `SeaPearl.update_features!` works, maybe @tomsander1998 can explain to us ?
